# 并行策略
parallel:
  fully_shard_parallel_size: auto
  pregather: true
  fsdp_plan:
    apply_modules:
      - language_model.layers.{*}
    param_dtype: bf16
    reduce_dtype: fp32

# 数据相关配置
data:
  dataset_param:
    dataset_type: mosstts_delay

    # 数据预处理
    preprocess_parameters:
      model_name_or_path: &HF_MODEL_LOAD_PATH /MOSS-TTS # 替换为hf权重

    basic_parameters:
      dataset_dir: &DATASET_PATH /data/train_with_codes.jsonl # 替换为数据集路径

  # 数据加载
  dataloader_param:
    pin_memory: true
    shuffle: false
    dataloader_mode: sampler
    drop_last: true
    sampler_type: BaseRandomBatchSampler
    num_workers: 8
    collate_param:
      model_name: mosstts_delay

# 模型配置
model:
  model_id: moss_tts_delay
  model_name_or_path: &HF_MODEL_LOAD_PATH /MOSS-TTS # 替换为hf权重
  trust_remote_code: true
  loss_cfg:
    loss_type: dict

# 训练配置
training:
  adam_beta2: 0.95
  micro_batch_size: 1
  gradient_accumulation_steps: 1
  seed: 42
  lr: 1.0e-5
  lr_decay_style: linear
  lr_warmup_ratio: 0.03
  weight_decay: 0.1
  train_iters: 10000
  clip_grad: 1.0
  init_model_with_meta_device: false
  optimizer: adamw
  adam_fused: false
  save_interval: 10000
  # load: load_path
  save: ./save_dir
  use_deter_comp: false
  allow_hf32: false
  # 2. 模型精度
  plugin:
    - mindspeed_mm/fsdp/models/moss_tts_delay
    - mindspeed_mm/fsdp/data/datasets/moss_tts_delay

# 工具配置
tools:
  profile:
    enable: false
    profile_type: static
    ranks: [0]
    static_param:
      level: level1
      with_stack: false
      with_memory: false
      record_shapes: false
      with_cpu: true
      save_path: ./profiling
      start_step: 10
      end_step: 11
      data_simplification: false
      aic_metrics_type: PipeUtilization
  memory_profile:
      enable: false
      start_step: 1
      end_step: 2
      save_path: ./memory_snapshot
      dump_ranks: [0]
      stacks: all
      max_entries: null
      mem_info: false
